# Generated by Django 3.2.7 on 2022-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('en_route', 'en_route'), ('delivered', 'delivered')], default='pending', max_length=10),
        ),
    ]
